# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
arch: i386
warnings_are_errors: false

addons:
  apt:
    packages:
      - libudunits2-dev
