on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: coverage

jobs:
  coverage:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Test coverage
        run: |
          install.packages("covr")
          covr::codecov()
        shell: Rscript {0}
